### ISSUE TITLE
Blank in graph in dasboard 

### ISSUE THREAD

**Issue by steve-gil** [poctob/OSTEquipmentPlugin#1]
![error dasboard osticket equiment](https://cloud.githubusercontent.com/assets/8042532/3450999/cd3858fe-0189-11e4-956b-8d7d36c6de95.jpg)
Error dasboard

**Comment by poctob** [comment]
List your OS, web server version, database type and version, PHP version and OSTicket version. 
Also, please provide the URL you were trying to access when you got a blank page and the web server error log.

**Comment by poctob** [comment]
Closing for no response.

**Comment by steve-gil** [comment]
Clearos 6.5 
Webserver 
osticket 1.9.2
PHP 5.3.3 (cli) (built: Nov  8 2014 15:15:39)
Server version: Apache/2.2.15 (Unix)
Server: Main Database (127.0.0.1 via TCP/IP)
Server type: MySQL
Server version: 5.1.73 - Source distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

i'm sorry im late to respon...
