### ISSUE TITLE
Remove key property from `ost_equipment`.`name`

### ISSUE THREAD

**Issue by aarobc** [poctob/OSTEquipmentPlugin#10]
This prevents Using the same name on multiples of the same device. 

In cases where you have many of the exact same devices there is really no point to trying to come up with unique names for every single one. That's what the Asset ID is for. 

I've actually modified my current configuration with said changes and it's much better. I'll try to commit the changes as soon as I figure out git better.

**Comment by poctob** [comment]
Be careful, I think the name field is being used in the dynamic form generation. If you use the same name for multiple equipment items you may not show correct trouble tickets associated with those items.

**Comment by poctob** [comment]
Removed in the upstream
