### ISSUE TITLE
View Ticket By Status

### ISSUE THREAD

**Issue by helmyshankly** [poctob/OSTEquipmentPlugin#11]
For Asset Management, we would like to keep track of the item movement. This mod was great except one I cannot see (on my ticket panel) whether ticket for Asset Transfer/Management status is ongoing/ pending/ delivered and so on. I found custom form for Equipment but the form only initialize in the beginning when open new ticket. 

Is it possible if admin can set status for it using admin panel, and perhaps can see its status from ticket panel

**Comment by helmyshankly** [comment]
@poctob please advise

**Comment by poctob** [comment]
This sounds like a good addition.  Please elaborate more on your desired functionality.  Would be transfer between departments existing in the OSTicket or transfer to the customer.  How do you envision this working?

**Comment by helmyshankly** [comment]
First, we would like to be able to view ticket status for asset management in the staff panel to view progress. Please add some customizable equipment status.

**Comment by poctob** [comment]
Equipment status is already customizable, you have to add all status items yourself.

**Comment by helmyshankly** [comment]
Yes but it is not view-able at staff panel.. i need to click ticket number to view its status.

**Comment by poctob** [comment]
The dashboard was added for the application.
