### ISSUE TITLE
Live Search Problem

### ISSUE THREAD

**Issue by mumulauraky** [poctob/OSTEquipmentPlugin#14]
Hi, 
after the installation of your good plugin i have a problem with the live search function. 
If i click to open a new ticket then its open a new windows with the Lookup or create a user function. If i tipp a name of my users is in the "live search field" i get no more answers from the system. 

What have i do wrong?

Thanks a lot!

**Comment by slm4996** [comment]
The css being inserted at the top of include/plugins/equipment/equipment.php is breaking the json response. You remove, do not comment out, the first line of that file temporarily until a fix is posted.

**Comment by poctob** [comment]
That has been fixed in the upstream and is implemented in the upcoming new release..
