### ISSUE TITLE
Long Response box tiny?

### ISSUE THREAD

**Issue by ChrisOFNA** [poctob/OSTEquipmentPlugin#15]
After I installed the Equipment Log this was happening.

![problem](https://cloud.githubusercontent.com/assets/8354898/3801660/a660826e-1c06-11e4-8863-b950f2dc5088.jpg)

Here is the log from that day:
[Mon Aug 04 08:14:19.087332 2014] [core:warn] [pid 12415] AH00045: child process 26414 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586854 2014] [core:warn] [pid 12415] AH00045: child process 17160 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586880 2014] [core:warn] [pid 12415] AH00045: child process 25468 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586894 2014] [core:warn] [pid 12415] AH00045: child process 22716 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586906 2014] [core:warn] [pid 12415] AH00045: child process 15958 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586918 2014] [core:warn] [pid 12415] AH00045: child process 27219 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586931 2014] [core:warn] [pid 12415] AH00045: child process 12899 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586938 2014] [core:warn] [pid 12415] AH00045: child process 30073 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586945 2014] [core:warn] [pid 12415] AH00045: child process 27075 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:19.586952 2014] [core:warn] [pid 12415] AH00045: child process 18102 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.587952 2014] [core:warn] [pid 12415] AH00045: child process 26414 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588004 2014] [core:warn] [pid 12415] AH00045: child process 17160 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588016 2014] [core:warn] [pid 12415] AH00045: child process 25468 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588028 2014] [core:warn] [pid 12415] AH00045: child process 22716 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588039 2014] [core:warn] [pid 12415] AH00045: child process 15958 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588049 2014] [core:warn] [pid 12415] AH00045: child process 27219 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588060 2014] [core:warn] [pid 12415] AH00045: child process 12899 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588070 2014] [core:warn] [pid 12415] AH00045: child process 30073 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588081 2014] [core:warn] [pid 12415] AH00045: child process 27075 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:20.588091 2014] [core:warn] [pid 12415] AH00045: child process 18102 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590151 2014] [core:warn] [pid 12415] AH00045: child process 26414 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590190 2014] [core:warn] [pid 12415] AH00045: child process 17160 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590203 2014] [core:warn] [pid 12415] AH00045: child process 25468 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590214 2014] [core:warn] [pid 12415] AH00045: child process 22716 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590225 2014] [core:warn] [pid 12415] AH00045: child process 15958 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590236 2014] [core:warn] [pid 12415] AH00045: child process 27219 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590246 2014] [core:warn] [pid 12415] AH00045: child process 12899 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590257 2014] [core:warn] [pid 12415] AH00045: child process 30073 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590267 2014] [core:warn] [pid 12415] AH00045: child process 27075 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:22.590278 2014] [core:warn] [pid 12415] AH00045: child process 18102 still did not exit, sending a SIGTERM
[Mon Aug 04 08:14:24.592324 2014] [core:error] [pid 12415] AH00046: child process 26414 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592378 2014] [core:error] [pid 12415] AH00046: child process 17160 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592394 2014] [core:error] [pid 12415] AH00046: child process 25468 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592409 2014] [core:error] [pid 12415] AH00046: child process 22716 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592423 2014] [core:error] [pid 12415] AH00046: child process 15958 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592437 2014] [core:error] [pid 12415] AH00046: child process 27219 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592451 2014] [core:error] [pid 12415] AH00046: child process 12899 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592470 2014] [core:error] [pid 12415] AH00046: child process 30073 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592478 2014] [core:error] [pid 12415] AH00046: child process 27075 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:24.592486 2014] [core:error] [pid 12415] AH00046: child process 18102 still did not exit, sending a SIGKILL
[Mon Aug 04 08:14:25.639726 2014] [mpm_prefork:notice] [pid 12415] AH00169: caught SIGTERM, shutting down
[Mon Aug 04 08:15:58.033311 2014] [ssl:warn] [pid 26064] AH01906: www.example.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Aug 04 08:15:58.033460 2014] [ssl:warn] [pid 26064] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 04 08:15:58.044786 2014] [suexec:notice] [pid 26064] AH01232: suEXEC mechanism enabled (wrapper: /opt/lampp/bin/suexec)
[Mon Aug 04 08:15:58.171008 2014] [auth_digest:notice] [pid 26070] AH01757: generating secret for digest authentication ...
[Mon Aug 04 08:15:59.001873 2014] [ssl:warn] [pid 26070] AH01906: www.example.com:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Mon Aug 04 08:15:59.001938 2014] [ssl:warn] [pid 26070] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 04 08:15:59.002196 2014] [lbmethod_heartbeat:notice] [pid 26070] AH02282: No slotmem from mod_heartmonitor
[Mon Aug 04 08:15:59.214583 2014] [mpm_prefork:notice] [pid 26070] AH00163: Apache/2.4.9 (Unix) OpenSSL/1.0.1g PHP/5.5.11 mod_perl/2.0.8-dev Perl/v5.16.3 configured -- resuming normal operations
[Mon Aug 04 08:15:59.214650 2014] [core:notice] [pid 26070] AH00094: Command line: '/opt/lampp/bin/httpd -E /opt/lampp/logs/error_log -D SSL -D PHP'
[Mon Aug 04 10:04:14.362485 2014] [:error] [pid 26075] [client 192.168.1.137:57482] script '/opt/lampp/htdocs/osticket/scp/apps.php' not found or unable to stat, referer: http://192.168.1.12/osticket/scp/index.php
[Mon Aug 04 10:04:14.628130 2014] [:error] [pid 26075] [client 192.168.1.137:57482] script '/opt/lampp/htdocs/osticket/scp/apps.php' not found or unable to stat, referer: http://192.168.1.12/osticket/scp/apps.php
[Mon Aug 04 10:04:31.538880 2014] [:error] [pid 27842] [client 192.168.1.137:57486] script '/opt/lampp/htdocs/osticket/scp/apps.php' not found or unable to stat, referer: http://192.168.1.12/osticket/scp/equipment.php
[Mon Aug 04 10:04:31.607468 2014] [:error] [pid 27842] [client 192.168.1.137:57486] script '/opt/lampp/htdocs/osticket/scp/apps.php' not found or unable to stat, referer: http://192.168.1.12/osticket/scp/apps.php
[Mon Aug 04 10:06:25.716000 2014] [:error] [pid 26075] [client 192.168.1.137:57496] script '/opt/lampp/htdocs/osticket/scp/apps.php' not found or unable to stat, referer: http://192.168.1.12/osticket/scp/equipment.php
[Mon Aug 04 10:06:25.795795 2014] [:error] [pid 26075] [client 192.168.1.137:57496] script '/opt/lampp/htdocs/osticket/scp/apps.php' not found or unable to stat, referer: http://192.168.1.12/osticket/scp/apps.php

Any idea what might have happened?

**Comment by poctob** [comment]
I don't see this problem in the upstream version, but it also looks like you modified default form for the equipment.  The plugin is not going to work correctly if that form is missing its variables that were setup there initially.

**Comment by ChrisOFNA** [comment]
I didn't modify the default form for equipment.  That is a form for something totally different.  It affected every other form I have after I installed the mod..  The equipment form is as it came.  Sorry, should of made that more clear.

**Comment by poctob** [comment]
Try a workaround in this post, see if it fixes it:

https://github.com/poctob/OSTEquipmentPlugin/issues/14
