### ISSUE TITLE
Assign Equipment to User

### ISSUE THREAD

**Issue by rowlandan25** [poctob/OSTEquipmentPlugin#16]
First off, I love how this looks! I will be putting it on my new system when I get it deployed next week.

I would like to add an enhancement idea.  We have over 1500 devices on our network (just desktop and laptops) not to mention other networking equipment (printers, switches, etc) and peripherals (projectors, digital boards, etc).  If I were to add all of this stuff into the system, my staff would spend 10 minutes just looking for what they want to report is having an error.

I would like to see the ability to assign an object a user in the system (whether it is a local user or a LDAP user), and have any assigned devices at the top of the equipment list.  This way if they are using a device in another room they can still put a ticket in for it, but if it is their equipment that is broken it is right there.

**Comment by poctob** [comment]
Would a user be the staff or did you mean any user?

**Comment by rowlandan25** [comment]
Any registered end user (not a staff member)

**Comment by poctob** [comment]
Equipment list on the create ticket page can't be changed or modified dynamically without changing OSTicket core files.  The list is stored in the database and is updated and deleted when a piece of equipment is added or deleted.  A workaround would be to add user name to the asset_id and then change asset_id field to typeahead.
