### ISSUE TITLE
Equipment Details/Recurring Ticket

### ISSUE THREAD

**Issue by JDFueled** [poctob/OSTEquipmentPlugin#2]
Improvement Ideas:

+1 Awesome work! This is an amazing step in the right direction!! Giving osTicket the power of asset management will make it an unstoppable force in the ticketing world!! One or two suggestions moving forward though.  Add the ability to "schedule a recurring ticket" for the equipment, prefilled reminder or task, with attachments, and allow the admin to create custom forms/fields for the equipment(i.e. serial numbers, model name, profile pic of the equipment/hardware, etc., etc.), this way it won't be industry specific!! :-D

**Comment by poctob** [comment]
Candidate for the next release.
1.  Recurring ticket scheduling for an item.
2. Custom form for an item.

**Comment by DaAntidote** [comment]
+1 on the recurring ticket scheduler. GREAT IDEA!!

**Comment by poctob** [comment]
custom form
https://github.com/poctob/OSTEquipmentPlugin/commit/54abcdc2a013eae12010018567746f14347f29f5

**Comment by DaAntidote** [comment]
Ok.

on a fresh 1.9.2 osticket install I followed your new instructions until
Step F.

All is well until After step F. I click equipment manager and see the
attached..

The following is a copy paste of the text at the top of the page. Also
attached is the post equipment install db export. This install used table
prefix _192aost__ Hope this helps.

[CREATE TABLE IF NOT EXISTS `192aost_equipment` ( `equipment_id` int(10)
unsigned NOT NULL AUTO_INCREMENT, `category_id` int(10) unsigned NOT NULL
DEFAULT '0', `status_id` int(10) unsigned NOT NULL DEFAULT '0',
`ispublished` tinyint(1) unsigned NOT NULL DEFAULT '0', `asset_id`
varchar(255) NOT NULL, `description` text, `notes` text, `created` date NOT
NULL, `updated` date NOT NULL, `is_active` tinyint(1) NOT NULL DEFAULT '1',
`name` varchar(255) DEFAULT NULL, PRIMARY KEY (`equipment_id`), UNIQUE KEY
`asset_id_UNIQUE` (`asset_id`) ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT
CHARSET=utf8; CREATE TABLE IF NOT EXISTS `192aost_equipment_category` (
`category_id` int(10) unsigned NOT NULL AUTO_INCREMENT, `ispublic`
tinyint(1) unsigned NOT NULL DEFAULT '0', `name` varchar(125) DEFAULT NULL,
`description` text NOT NULL, `notes` tinytext NOT NULL, `created` date NOT
NULL, `updated` date NOT NULL, PRIMARY KEY (`category_id`), KEY `ispublic`
(`ispublic`) ) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8] You
have an error in your SQL syntax; check the manual that corresponds to your
MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT
EXISTS `192aost_equipment_category` ( `category_id` int(10' at line 17
Error parsing SQL schema! Get help from developers (#4)
First run configuration error. Unable to create database tables!

[image: Inline images 1]

On 22 July 2014 06:39, poctob notifications@github.com wrote:

> custom form
> 54abcdc
> https://github.com/poctob/OSTEquipmentPlugin/commit/54abcdc2a013eae12010018567746f14347f29f5
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poctob/OSTEquipmentPlugin/issues/2#issuecomment-49684952
> .

## 

Mart Hough
p.+925 1798 9025

**Comment by poctob** [comment]
should be fixed now
https://github.com/poctob/OSTEquipmentPlugin/archive/master.zip

**Comment by DaAntidote** [comment]
I deleted the old equipment folder
I extracted in the new zip file
renamed to it to equipment

the error text has gone but when I go to the equipment dashboard I get a
blank white screen..

In the url I have
http://localhost/192/scp/dispatcher.php/equipment/dashboard/

Is the path after the dispatcher.php a folder? I dont have a dashboard
folder under equipment.

Not sure what to give you to help troubleshoot that but here is my install
config incase its something to do with my PHP version or something.

Server InformationosTicket Versionv1.9.2 (4827655)Server SoftwareApache/2.4.9
(Win32) OpenSSL/1.0.1g PHP/5.5.11PHP Version5.5.11MySQL Version5.6.16PHP
ExtensionsYESgdlibUsed for image manipulation and PDF printingNOimapUsed
for email fetchingYESxmlXML APIYESxml-domUsed for HTML email processingYES
jsonImproves performance creating and processing JSONYESgettextImproves
performance for non US-English configurationsYESmbstringHighly recommended
for non western european language contentYESpharHighly recommended for
plugins and language packsPHP Settingscgi.fix_pathinfo ="1" is recommended
if AJAX is not workingDatabase UsageDatabase Space Used5.98 MiBDatabase
Space for Attachments0.01 MiB

On 22 July 2014 18:35, poctob notifications@github.com wrote:

> should be fixed now
> https://github.com/poctob/OSTEquipmentPlugin/archive/master.zip
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poctob/OSTEquipmentPlugin/issues/2#issuecomment-49732632
> .

## 

Mart Hough
p.+925 1798 9025

**Comment by poctob** [comment]
Did you rename the folder last time?

Is the rest of your OST working?

Check XXX_plugin table in the database, make sure that Install_path
matches your actual equipment plugin path.

**Comment by DaAntidote** [comment]
Did you rename the folder last time?

_Yes_

Is the rest of your OST working?

_Yes it appears to be_

Check XXX_plugin table in the database, make sure that Install_path
matches your actual equipment plugin path.

_Yes it does._

SQL EXPORT ATTACHED. I did a few attempts. Deleted the entire install,
restored fresh files, did a whole new installation (192bost) as well. But
all come to the same result.

On 22 July 2014 22:31, poctob notifications@github.com wrote:

> Did you rename the folder last time?
> 
> Is the rest of your OST working?
> 
> Check XXX_plugin table in the database, make sure that Install_path
> matches your actual equipment plugin path.
> 
> On 07/22/2014 12:23 PM, FluffyLightEngineering wrote:
> 
> > I deleted the old equipment folder
> > I extracted in the new zip file
> > renamed to it to equipment
> > 
> > the error text has gone but when I go to the equipment dashboard I get a
> > blank white screen..
> > 
> > In the url I have
> > http://localhost/192/scp/dispatcher.php/equipment/dashboard/
> > 
> > Is the path after the dispatcher.php a folder? I dont have a dashboard
> > folder under equipment.
> > 
> > Not sure what to give you to help troubleshoot that but here is my
> > install
> > config incase its something to do with my PHP version or something.
> > 
> > Server InformationosTicket Versionv1.9.2 (4827655)Server
> > SoftwareApache/2.4.9
> > (Win32) OpenSSL/1.0.1g PHP/5.5.11PHP Version5.5.11MySQL Version5.6.16PHP
> > ExtensionsYESgdlibUsed for image manipulation and PDF printingNOimapUsed
> > 
> > for email fetchingYESxmlXML APIYESxml-domUsed for HTML email
> > processingYES
> > jsonImproves performance creating and processing JSONYESgettextImproves
> > performance for non US-English configurationsYESmbstringHighly
> > recommended
> > for non western european language contentYESpharHighly recommended for
> > plugins and language packsPHP Settingscgi.fix_pathinfo ="1" is
> > 
> > recommended
> > if AJAX is not workingDatabase UsageDatabase Space Used5.98 MiBDatabase
> > Space for Attachments0.01 MiB
> > 
> > On 22 July 2014 18:35, poctob notifications@github.com wrote:
> > 
> > > should be fixed now
> > > https://github.com/poctob/OSTEquipmentPlugin/archive/master.zip
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > <
> > > https://github.com/poctob/OSTEquipmentPlugin/issues/2#issuecomment-49732632
> > > 
> > > .
> > 
> > ## 
> > 
> > Mart Hough
> > p.+925 1798 9025
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/poctob/OSTEquipmentPlugin/issues/2#issuecomment-49762840
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poctob/OSTEquipmentPlugin/issues/2#issuecomment-49763961
> .

## 

Mart Hough
p.+925 1798 9025

**Comment by poctob** [comment]
MySQL based recurring functionality was added.
