### ISSUE TITLE
The Applications Tab is a link which goes nowhere 1.9.3a

### ISSUE THREAD

**Issue by DaAntidote** [poctob/OSTEquipmentPlugin#21]
Bug
On admin panel if I click on "Applications" - the tab I get a 404 error.
If I click on equipment under the applications tab it works fine.

Would it be better to make the Equipment plugin the title of the tab, rather than a child of the applications tab?

**Comment by poctob** [comment]
Can't do anything about that one.  This is OSTicket core bug.
https://github.com/osTicket/osTicket-1.8/issues/1072
