### ISSUE TITLE
Installation fails to update tables in MySQL

### ISSUE THREAD

**Issue by DaAntidote** [poctob/OSTEquipmentPlugin#23]
After accidently editing the Equipment form I decided to reinstall a fresh instance of ost and the plugin on my test box.
Twice now it has not installed correctly with the error;

[ALTER TABLE `ost_equipment` ADD COLUMN `asset_id` VARCHAR(255) NOT NULL, ADD UNIQUE KEY `asset_id_UNIQUE` (`asset_id`), CHANGE COLUMN `name` `name` VARCHAR(255) NULL , DROP INDEX `name`] Unknown column 'name' in 'ost_equipment'[call `ost_UpgradeEquipmentFormFields`] Subquery returns more than 1 row
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables!

It has also created a duplicate Equipment Form.

![image](https://cloud.githubusercontent.com/assets/7599444/3903484/82564b0c-22cc-11e4-9fac-de3a32bb62ee.png)

This is a screenshot of the table in question after the plugin installation.

![image](https://cloud.githubusercontent.com/assets/7599444/3903533/1f0d91bc-22cd-11e4-9c92-45e696f648c3.png)

![image](https://cloud.githubusercontent.com/assets/7599444/3903567/81c6b130-22cd-11e4-8013-e8245ea4e025.png)

**Comment by poctob** [comment]
The error message is expected and the equipment table looks fine.  This would normally happen if you try to reinstall the database over the existing equipment tables.  You should be able to safely delete second Equipment form.

**Comment by DaAntidote** [comment]
Ok. but this was a fresh install..? I'll try again.

On 13 August 2014 18:22, poctob notifications@github.com wrote:

> The error message is expected and the equipment table looks fine. This
> would normally happen if you try to reinstall the database over the
> existing equipment tables. You should be able to safely delete second
> Equipment form.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poctob/OSTEquipmentPlugin/issues/23#issuecomment-52040893
> .

## 

Mart Hough
p.+925 1798 9025

**Comment by slm4996** [comment]
This happens on a fresh install as well, and the error message never goes away. This is not ready to be closed.

**Comment by slm4996** [comment]
On doing a little  more research it appears that if you have an existing form names 'Equipment' this error occurs and does not go away with a fresh install. Removing the plugin, tables and it's forms. Along with my form name Equipment and it installs fine.

**Comment by poctob** [comment]
Go to Admin->Manage->Forms,  make sure that you only have one form named Equipment
Go to Admin->Manage->List,  make sure that you only have one list named equipment and only one named equipment_status

**Comment by PaulMcGuinness** [comment]
That fixed it... multiple Lists.

Also discovered what caused it.... Hit 'Enable' twice.

**Comment by poctob** [comment]
Actually it is caused by a bug in the installation script where it doesn't register the plugin properly.  So next time you refresh the page it thinks that it needs to upgrade and attempts to recreate all database data.

**Comment by DaAntidote** [comment]
Hi,
I'm still struggling with this issue. I'm preparing a production environment and on a fresh install the errors are there.
Admin->Manage->Forms, I have only one form named Equipment
Admin->Manage->List, I have one list named equipment and only one named equipment_status

I didn't hit enable twice.

My equipment dashboard looks all messed up and non functional.

Refresh and browsing on an alternate PC don't resolve the issue.

Restarting Apache and mysql didn't make a difference either.

![screenshot](https://cloud.githubusercontent.com/assets/7599444/4147497/37135c62-3419-11e4-8430-d13b0e05dee6.png)

**Comment by DaAntidote** [comment]
I only have one entry in my plugin table

**Comment by DaAntidote** [comment]
I downloaded the plugin zip file today

**Comment by poctob** [comment]
Looks like you have downloaded an untested upstream code.  I would suggest waiting for a release.

**Comment by DaAntidote** [comment]
oh of course.

Well I guess I just did some testing for you!

On 4 September 2014 17:37, poctob notifications@github.com wrote:

> Looks like you have downloaded an untested upstream code. I would suggest
> waiting for a release.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poctob/OSTEquipmentPlugin/issues/23#issuecomment-54458257
> .

## 

Mart Hough
p.+925 1798 9025

**Comment by poctob** [comment]
New testing release is out.
https://github.com/poctob/OSTEquipmentPlugin/releases/tag/1.9.3b-0.3rc
