### ISSUE TITLE
Error on top and middle of page.

### ISSUE THREAD

**Issue by ChrisOFNA** [poctob/OSTEquipmentPlugin#27]
Hey guy(s),

   I'm getting what looks to be a SQL error at the top and middle of the page after installation (see attached).  Any reason this might be happening?
![ostproblem](https://cloud.githubusercontent.com/assets/8354898/3970856/7048ce2e-27ce-11e4-9c2d-b12fa9f06ad7.jpg)

**Comment by poctob** [comment]
https://github.com/poctob/OSTEquipmentPlugin/issues/23

Remove any forms named Equipment and try again.  You may still get a similar error on the initial install/update, but it should go away on page reload.

**Comment by ChrisOFNA** [comment]
Which folder should I be removing these from?  All of them in the osticket directory?

**Comment by poctob** [comment]
Not from the source.  Go to Admin Panel -> Manage -> Forms, see if you have more than one Equipment form under Custom Forms.

**Comment by ChrisOFNA** [comment]
I don't, only one.  I did get rid of one error by going to changing the custom form name for the plugin to -None-.
![ostproblem](https://cloud.githubusercontent.com/assets/8354898/3971063/3dd35408-27d0-11e4-924b-7ca0d680d0f9.jpg)

**Comment by poctob** [comment]
Delete other Equipment form too.

**Comment by ChrisOFNA** [comment]
How?  It has no delete box on the side.

**Comment by poctob** [comment]
Can you rename it?

**Comment by ChrisOFNA** [comment]
I did, it did nothing.
![ostproblem](https://cloud.githubusercontent.com/assets/8354898/3971189/5e8c0ca2-27d1-11e4-8464-322f9644680e.jpg)

**Comment by poctob** [comment]
Can you check your database and look into %TABLE_PREFIX%plugin table.  See how many entries you have there for equipment_manager.  You should only have one.
