### ISSUE TITLE
Reoccuring ticket?

### ISSUE THREAD

**Issue by ChrisOFNA** [poctob/OSTEquipmentPlugin#29]
![reoccuringticket](https://cloud.githubusercontent.com/assets/8354898/4010725/131016c6-29fa-11e4-9e1b-e314bedb14d1.png)
I have created a ticket for this piece of equipment but nothing comes up to select for the ticket.  Any idea what it can be?  I tried it with an open and closed ticket.

**Comment by poctob** [comment]
Is the ticket showing up in the open or closed ticket tables under equipment or category page?

**Comment by ChrisOFNA** [comment]
![reoccuringticke3](https://cloud.githubusercontent.com/assets/8354898/4010778/06d8c578-29fb-11e4-9f3a-8fdd59a9083a.png)
![reoccuringticket2](https://cloud.githubusercontent.com/assets/8354898/4010779/06e6d3ac-29fb-11e4-8300-c7908be287d2.png)
Is this where you were asking?

**Comment by poctob** [comment]
Try this patch
https://raw.githubusercontent.com/poctob/OSTEquipmentPlugin/16e6f9dae3c3c9a69d35969e9a406a9b2a66be38/views/recurring/editForm.html.twig

it goes to [Equipment Plugin Root]/views/recurring/

**Comment by ChrisOFNA** [comment]
It didn't fixed it.  Still can't select a ticket.

**Comment by poctob** [comment]
can you check for server errors and javascript errors in the browser (right click->Inspect Element in Chrome)?

**Comment by ChrisOFNA** [comment]
Nothing out of the ordinary from what I seen. I use Firefox though so what field would I be looking at?

**Comment by poctob** [comment]
[OSTicketRootURL]scp/dispatcher.php/equipment/recurring/listTicketsJson

try this link in the browser and let me know if anything comes back

**Comment by ChrisOFNA** [comment]
It's empty.

**Comment by poctob** [comment]
Do you at least get empty square brackets?

**Comment by ChrisOFNA** [comment]
![reoccuringticket4](https://cloud.githubusercontent.com/assets/8354898/4011581/b315d240-2a05-11e4-8d39-4a61e6ca61e1.png)
This is all I get.

**Comment by poctob** [comment]
Do you have any SQL errors under admin->Dashboard->System Logs?

**Comment by ChrisOFNA** [comment]
![reoccuringticket5](https://cloud.githubusercontent.com/assets/8354898/4011757/60e4e2ca-2a07-11e4-8a29-ec683e1ff2e0.png)
Nope.

**Comment by poctob** [comment]
OK.  I'm out of ideas.  Can you forward me your DB dump and zip OSTicket directory?

**Comment by ChrisOFNA** [comment]
I emailed you my DB and current OST config.  Hopefully your email doesn't block 25mb files.

**Comment by poctob** [comment]
https://raw.githubusercontent.com/poctob/OSTEquipmentPlugin/786c1c1c7557107f5aab775e0aaa135fc2b7d00c/include/model/EquipmentTicket.php

goes to [Equipment Plugin Root]/include/model/

**Comment by ChrisOFNA** [comment]
Sorry for the late response.

That worked!  What was the issue in that file?

**Comment by poctob** [comment]
It wasn't accounting for deleted tickets.
