### ISSUE TITLE
Throws a number of SQL errors when enabling on 1.9.3

### ISSUE THREAD

**Issue by PaulMcGuinness** [poctob/OSTEquipmentPlugin#30]
[ALTER TABLE `ost_equipment` ADD COLUMN `asset_id` VARCHAR(255) NOT NULL, ADD UNIQUE KEY `asset_id_UNIQUE` (`asset_id`), CHANGE COLUMN `name` `name` VARCHAR(255) NULL , DROP INDEX `name`] Unknown column 'name' in 'ost_equipment'[call `ost_UpgradeEquipmentFormFields`] Subquery returns more than 1 row
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables!

**Comment by poctob** [comment]
https://github.com/poctob/OSTEquipmentPlugin/issues/23

**Comment by PaulMcGuinness** [comment]
Not caused by that - I have no forms called equipment, and have double-checked within the MySQL database.
