### ISSUE TITLE
Bug. Open and closed tickets are not appearing under equipment

### ISSUE THREAD

**Issue by DaAntidote** [poctob/OSTEquipmentPlugin#32]
When viewing equipment the open and closed ticket summaries are not updating. The tickets are not showing up when opened, nor when closed.

It seemed to be working fine, but stopped. Between seeming to work fine and not seeming to work fine I tried deleting an equipment. I also tried changing the equipment field in the equipment from from drop down to typeahead, but neither of those should make any difference.

I swapped back to drop down to associate tickets but it didn't make a difference.

I am testing version 1.9.3a from about two weeks ago.

Im working on getting an SQL export.

**Comment by poctob** [comment]
check if this file is different on your install:
https://raw.githubusercontent.com/poctob/OSTEquipmentPlugin/master/include/controller/Controller.php

**Comment by DaAntidote** [comment]
No it wasn't. I've replaced it with the above file and the issue seems to have gone away.

Thank you!
