### ISSUE TITLE
database error on web host

### ISSUE THREAD

**Issue by rxm0026** [poctob/OSTEquipmentPlugin#33]
The plugin works great on localhost but if you use a web host site, this error appears and you can't open osticket's admin side and client side too.

[ALTER TABLE `thesis12_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) NOT NULL , ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` INT NULL AFTER `staff_id` DROP INDEX `name`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP INDEX `name`' at line 5[CREATE PROCEDURE `thesis12_Equipment_Copy_Form_Entry`(p_ticket_id INT, p_new_ticket_id INT) BEGIN DECLARE n INT DEFAULT 0; DECLARE i INT DEFAULT 0; DECLARE l_id INT; DECLARE l_new_id INT; DROP TEMPORARY TABLE IF EXISTS tmp_table2; CREATE TEMPORARY TABLE tmp_table2 SELECT \* FROM thesis12_form_entry WHERE object_id = p_ticket_id AND `object_type` = 'T'; SET SQL_SAFE_UPDATES=0; ALTER TABLE tmp_table2 modify column id int; SELECT COUNT(*) FROM tmp_table2 INTO n; SET i = 0; WHILE i

**Comment by poctob** [comment]
Where are your site and the database hosted?
