### ISSUE TITLE
Import option

### ISSUE THREAD

**Issue by natecluff** [poctob/OSTEquipmentPlugin#34]
Not seeing any activity since July on this project so I hope it is still alive.  I recently incorporated the Equipment Managment plugin into my OSticket install.  It looks like something I might be able to use but would like to know if there is any way to import data.

**Comment by poctob** [comment]
Not sure what date you're seeing, but there were quite a few commits since July.
In any case, there is no automatic data import option right now.  You will have to work directly with the database to pull in external data.
