### ISSUE TITLE
SQL error when I activate the plugin

### ISSUE THREAD

**Issue by babywriter** [poctob/OSTEquipmentPlugin#36]
Here's what I'm getting after I activate the plugin:

![image](https://cloud.githubusercontent.com/assets/11045454/6229508/a3be8a80-b67d-11e4-95a0-e21d5e1984ea.png)

Any ideas? I'm using the newest version of OSTicket (1.9.5.1) and the plugin (1.9.4). I've tried this three times, and keep getting the same result.

Any help appreciated! Thanks!

**Comment by poctob** [comment]
Please update your MySQL server. See issue #35

**Comment by babywriter** [comment]
Thanks!

**Comment by babywriter** [comment]
I'm running 5.1.73, and I'm still getting the same error. Granted, MySQL is up around 5.6 currently, but I'm using a distribution (ClearOS) that's somewhat conservative with updates. osTicket says mySQL v5+ should work. 

Any other thoughts? I've got some Linux experience but I'm by no means a guru. Any help appreciated!

**Comment by poctob** [comment]
You'll need to take it up to at least 5.5.  This plugin is very database heavy in comparison to osTicket and it relies on many newer MySQL features not available before 5.5.

**Comment by babywriter** [comment]
Ok, thanks.
