### ISSUE TITLE
1.9.6 Issue with the 1.9.4 version of OSTEquipment

### ISSUE THREAD

**Issue by farmersWPSD** [poctob/OSTEquipmentPlugin#38]
After installation I get this after enabling:
[ALTER TABLE `wpost_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) NOT NULL , ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` INT NULL AFTER `staff_id` DROP INDEX `name`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP INDEX `name`' at line 5[CREATE VIEW `wpost_EquipmentTicketView` AS select `wpost_equipment_ticket`.`equipment_id` AS `equipment_id`, `wpost_equipment_ticket`.`ticket_id` AS `ticket_id`, `wpost_equipment_ticket`.`created` AS `created`, `wpost_equipment`.`category_id` AS `category_id`, `wpost_equipment`.`is_active` AS `is_active`, `wpost_ticket_status`.`state` AS `status` from `ost_equipment_ticket` left join `ost_equipment` on(`ost_equipment_ticket`.`equipment_id` = `ost_equipment`.`equipment_id`) left join `ost_ticket` on(`ost_equipment_ticket`.`ticket_id` = `ost_ticket`.`ticket_id`) left join `ost_ticket_status` on(`ost_ticket`.`status_id` = `ost_ticket_status`.`id`)] Table 'wpsdne5_osticket.ost_equipment_ticket' doesn't exist
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables! 

If I logout without disabling, I can't log back in.  I have to remove plugin manually and then remove the entry from the 'plugins' table.

**Comment by poctob** [comment]
This issue was fixed in the upstream patch.

You can download the latest from here:
https://github.com/poctob/OSTEquipmentPlugin

**Comment by farmersWPSD** [comment]
Sorry, but how would I install the upstream patch?  Just copy over the original, then do I need to run anything?

EDIT: I copied the new stuff over the old stuff and re-enabled plug-in, but still error, so I'm doing something wrong.

**Comment by farmersWPSD** [comment]
Tried new version.  Now this:

[ALTER TABLE `wpost_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) NOT NULL , ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` INT NULL AFTER `staff_id` DROP INDEX `name`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP INDEX `name`' at line 5[UPDATE `wpost_plugin` SET version = '0.4' WHERE `name`='Equipment Manager'] Unknown column 'version' in 'field list'
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables!

**Comment by poctob** [comment]
That's a bug in OSTicket core upgrader.  If you don't have any other
plugins installed, run this script after changing %TABLE_PREFIX% to your
tables prefix:

DROP TABLE IF EXISTS `%TABLE_PREFIX%plugin`;
CREATE TABLE `%TABLE_PREFIX%plugin` (
`id` int(11) unsigned not null auto_increment,
`name` varchar(30) not null,
`install_path` varchar(60) not null,
`isphar` tinyint(1) not null default 0,
`isactive` tinyint(1) not null default 0,
`version` varchar(64),
`installed` datetime not null,
primary key (`id`)
) DEFAULT CHARSET=utf8;

**Comment by farmersWPSD** [comment]
That appeared to fix it.  Thanks for your help.
