### ISSUE TITLE
MySQL error after installing Equipment Mod

### ISSUE THREAD

**Issue by mistressplaid** [poctob/OSTEquipmentPlugin#39]
Poctob,

We (my sys admin, really) installed your Equipment mod over osTicket (v1.9.9-1-gbe2f138) and we're getting a MySQL-related error on the top of each osTicket page. He's not sure what to do next. Any thoughts on how to fix this?

```
[ALTER TABLE `ost_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) 
NOT NULL , ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` 
INT NULL AFTER `staff_id` DROP INDEX `name`] You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version for the right syntax to use 
near 'DROP INDEX `name`' at line 5[DROP TRIGGER IF EXISTS `ost_equipment_ADEL`] 
You do not have the SUPER privilege and binary logging is enabled (you *might* want to use 
the less safe log_bin_trust_function_creators variable)
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables!'''
```

Also, when you click on Applications --> Equipment, the page CSS doesn't load and all of the links (in blue in the screenshot) don't work. 

This is the URL in case it helps you to know the path (changed my site name to "mysite" to keep our help desk private, but let me know if you need to know it and I'll message it to you):
http://help.borin.com/scp/dispatcher.php/equipment/dashboard/

Here is a screenshot of the error and the above URL's issues:
(https://cloud.githubusercontent.com/assets/1697124/8662513/50676c24-2975-11e5-8296-97f6f4d0eb33.jpg)

Any help you can give is very appreciated! Thank you! 
Jenn

**Comment by poctob** [comment]
Well, the problem description is in the error text "You do not have the SUPER privilege".  Your database user doesn't have sufficient privileges to drop and create triggers and probably do other stuff.

**Comment by poctob** [comment]
Closing for lack of response
