### ISSUE TITLE
Osticket v1.9.12 (19292ad) —  Up to date

### ISSUE THREAD

**Issue by eljagg** [poctob/OSTEquipmentPlugin#43]
Hi,
I am getting this error:

Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

I get this error after I have installed the Equipment plugin and I click on the "Applications" tab from the "My Preferences" Tab.

Also, I am not able to send email from the admin Diagnostics screen. I get the email sent message, but I am not getting the emails.  I would be most grateful for your help.

**Comment by poctob** [comment]
Did you check your webserver error log? Any relevant errors there?

**Comment by eljagg** [comment]
Thank you I got it sorted out. I went into php.ini and turned on SMTP and IMAP.
