### ISSUE TITLE
Broken Link "Application"

### ISSUE THREAD

**Issue by eljagg** [poctob/OSTEquipmentPlugin#45]
Hi,
After adding the Equipment Plugin. When ever I click on "Applications" Tab/Link I get the following:

Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

Can you please point me in the right direction on how to fix this issue. I will be rolling out OsTicket in my work environment soon. Thank you for your help.

**Comment by poctob** [comment]
What errors do you have in your web server log? Did you follow installation instructions on wiki?

**Comment by eljagg** [comment]
I Will try that and get back to you, thanks for the response.

**Comment by mavcom** [comment]
I also have that problem, and I followed the instructions on this page (https://github.com/poctob/OSTEquipmentPlugin).

**Comment by eljagg** [comment]
The installation instructions worked as listed.Thank you.

**Comment by eljagg** [comment]
Does anyone know of any plugin(s) that works with active directory? I would like to import existing users into Osticket.
