### ISSUE TITLE
Custom assets from databsae

### ISSUE THREAD

**Issue by josecobo1** [poctob/OSTEquipmentPlugin#46]
It's possible to store assets on another database? If it's possible (or not) where on the code of the plugin the asset list is getting?

Regards

**Comment by poctob** [comment]
It is possible in theory, but ti is closely tied to the OSTicket datbase, so there are too many placeses where they interlap. Look into models code for more information.

**Comment by josecobo1** [comment]
thank you

**Comment by josecobo1** [comment]
I'm sorry by the inconvenience,but I see there is a function called `db_query()` which runs a quiery on database. Where is defined? I've been looking on model files and don't find it I may need to modify it.

Thank

**Comment by poctob** [comment]
That's a part of OSTicket core. Essentially, it is just a wrapper around mysql-db-query http://php.net/manual/en/function.mysql-db-query.php

**Comment by josecobo1** [comment]
so this just get the credentials(user, password, host, database) from the osticket config?

**Comment by poctob** [comment]
yes
