### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by srmunn** [poctob/OSTEquipmentPlugin#48]
[ALTER TABLE `ost_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) NOT NULL , 
When I enable the plugin I get the following error appearing:

ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` INT NULL AFTER `staff_id` DROP INDEX `name`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP INDEX `name`' at line 5[CREATE TRIGGER `ost_equipment_ADEL` AFTER DELETE ON `ost_equipment` FOR EACH ROW BEGIN SET @pk=OLD.equipment_id; SET @list_pk=(SELECT id FROM `ost_list` WHERE name='equipment'); DELETE FROM `ost_list_items` WHERE list_id = @list_pk AND properties=CONCAT('',@pk); END] TRIGGER command denied to user 'xxxxxxxxx'@'10.0.1.245' for table 'ost_equipment'
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables!

I'm running Os Ticket v1.9.12 and MySQL v5.5.47

Thanks

**Comment by poctob** [comment]
Everything is in your error. Your database user doesn't have permissions to create triggers.
