### ISSUE TITLE
404 Not Found Application

### ISSUE THREAD

**Issue by genxlee** [poctob/OSTEquipmentPlugin#49]
I wanted to test this plugin on my Nginx web server but after completing every step in [Wiki](https://github.com/poctob/OSTEquipmentPlugin/wiki/Installation) aswell on [Admin panel](https://github.com/poctob/OSTEquipmentPlugin/wiki/Admin%20Panel) part I ran into error. Under applications there is Equipment but when accessing it shows 404, aswell it dosen't show up on tickets. 

Nginx error.log

```
2016/03/17 06:10:25 [error] 1234#0: *26922 "/var/www/tickets/scp/dispatcher.php/equipment/dashboard/index.php" is not found (20: Not a directory), client: x, server: , request: "GET /tickets/scp/dispatcher.php/equipment/dashboard/?_pjax=%23pjax-container HTTP/1.1", host: "riddi.eu", referrer: "https://riddi.eu/tickets/scp/index.php"

2016/03/17 06:10:25 [error] 1234#0: *26922 open() "/var/www/tickets/scp/dispatcher.php/equipment/dashboard/ajax.php/config/scp" failed (20: Not a directory), client: x, server: , request: "GET /tickets/scp/dispatcher.php/equipment/dashboard/ajax.php/config/scp HTTP/1.1", host: "riddi.eu", referrer: "https://riddi.eu/tickets/scp/dispatcher.php/equipment/dashboard/"

2016/03/17 06:10:25 [error] 1236#0: *26896 "/var/www/tickets/scp/dispatcher.php/equipment/dashboard/index.php" is not found (20: Not a directory), client: x, server: , request: "GET /tickets/scp/dispatcher.php/equipment/dashboard/ HTTP/1.1", host: "riddi.eu", referrer: "https://riddi.eu/tickets/scp/dispatcher.php/equipment/dashboard/"
```

PHP version:
`PHP 5.5.9-1ubuntu4.14 (cli)`

**Comment by poctob** [comment]
I never tried running it under Nginx, but usually 404 is a sign of misconfigured redirects. Under apache it happens when .htaccess has some messed up rules, so you probably should check the equivalent on nginx.

**Comment by genxlee** [comment]
Thank you, moved my osTicket to Apache web server.

**Comment by genxlee** [comment]
Okay, I got it working fine but I can't get dropdown while making new ticket like there is shown in youtube set-up video, I just have textbox where can I type equipment. 

Even when I type under equipment something I have already made it dosen't link it to Equipment application.

**Comment by poctob** [comment]
Did you set up categories and items? Do you have any errors in Apache log?

**Comment by genxlee** [comment]
Yes I did setup all catergories and items, Apache log dosen't show up anything.

**Comment by poctob** [comment]
Check if you have any errors under developer's tools javascript console in your browser.

**Comment by genxlee** [comment]
Console dosen't show up anything.

**Comment by girmangus** [comment]
when i click on the application->equipement or /userspice/erca/osttc19/scp/dispatcher.php/equipment/dashboard/ i got the 404 Not Found on ubuntu apache and accessing the tail of my log i found this 

127.0.0.1 - - [17/Jan/2017:17:46:11 +0300] "GET /userspice/erca/osttc19/scp/images/asc_desc.gif HTTP/1.1" 304 206 "http://localhost/userspice/erca/osttc19/scp/css/scp.css?901e5ea" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:11 +0300] "GET /userspice/erca/osttc19/scp/images/icons/new_ticket.gif HTTP/1.1" 304 206 "http://localhost/userspice/erca/osttc19/scp/css/scp.css?901e5ea" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:11 +0300] "GET /userspice/erca/osttc19/scp/images/icons/logs.gif HTTP/1.1" 304 206 "http://localhost/userspice/erca/osttc19/scp/css/scp.css?901e5ea" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:11 +0300] "GET /userspice/erca/osttc19/scp/images/icons/ticket_source_web.gif HTTP/1.1" 304 206 "http://localhost/userspice/erca/osttc19/scp/css/scp.css?901e5ea" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:11 +0300] "GET /userspice/erca/osttc19/scp/images/icons/teams.gif HTTP/1.1" 304 206 "http://localhost/userspice/erca/osttc19/scp/css/scp.css?901e5ea" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:11 +0300] "GET /userspice/erca/osttc19/scp/images/icons/user.gif HTTP/1.1" 304 207 "http://localhost/userspice/erca/osttc19/scp/css/scp.css?901e5ea" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:11 +0300] "GET /userspice/erca/osttc19/scp/images/icons/list_departments.gif HTTP/1.1" 304 206 "http://localhost/userspice/erca/osttc19/scp/css/scp.css?901e5ea" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:11 +0300] "GET /userspice/erca/osttc19/scp/autocron.php HTTP/1.1" 200 3135 "http://localhost/userspice/erca/osttc19/scp/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:13 +0300] "GET /userspice/erca/osttc19/scp/dispatcher.php/equipment/dashboard/?_pjax=%23pjax-container HTTP/1.1" 404 549 "http://localhost/userspice/erca/osttc19/scp/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
127.0.0.1 - - [17/Jan/2017:17:46:13 +0300] "GET /userspice/erca/osttc19/scp/dispatcher.php/equipment/dashboard/ HTTP/1.1" 404 549 "http://localhost/userspice/erca/osttc19/scp/dispatcher.php/equipment/dashboard/" "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:50.0) Gecko/20100101 Firefox/50.0"
