### ISSUE TITLE
Request not found

### ISSUE THREAD

**Issue by jrluz** [poctob/OSTEquipmentPlugin#50]
Need help I installed and followed the instruction here of installing equipment plugin but I am having problem when clicking the "application" tab in the agent panel.
![asdasd](https://cloud.githubusercontent.com/assets/18572381/14671548/f6139282-0724-11e6-94d3-a06809870e9d.PNG)
![error](https://cloud.githubusercontent.com/assets/18572381/14671549/f61867ee-0724-11e6-96be-1bd6e92fde4e.PNG)

Thanks in advance for any help.

**Comment by poctob** [comment]
Most likely the problem is with your .htaccess file not redirecting properly. Check your apache error log for more useful errors.

**Comment by jrluz** [comment]
Can you give me step to resolve this problem?

**Comment by poctob** [comment]
Not really, since I don't have access to your configuration or error logs.

**Comment by jrluz** [comment]
Hi poctob i am willing to let you remote my PC through Teamviewer. Please search and PM me on skype. luz.jerome12. Thank you in advance.

**Comment by poctob** [comment]
I'll PM you tomorrow.
