### ISSUE TITLE
MySQL related error on installation

### ISSUE THREAD

**Issue by Justproof** [poctob/OSTEquipmentPlugin#54]
This error appears after following along with the Equipment Plugin installation instructions. I'm using OSTicket 1.9.14. 
[ALTER TABLE `ost_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) NOT NULL , ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` INT NULL AFTER `staff_id` DROP INDEX `name`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DROP INDEX `name`' at line 5[CREATE VIEW `ost_EquipmentTicketView` AS select `ost_equipment_ticket`.`equipment_id` AS `equipment_id`, `ost_equipment_ticket`.`ticket_id` AS `ticket_id`, `ost_equipment_ticket`.`created` AS `created`, `ost_equipment`.`category_id` AS `category_id`, `ost_equipment`.`is_active` AS `is_active`, `ost_ticket_status`.`state` AS `status` from `ost_equipment_ticket` left join `ost_equipment` on(`ost_equipment_ticket`.`equipment_id` = `ost_equipment`.`equipment_id`) left join `ost_ticket` on(`ost_equipment_ticket`.`ticket_id` = `ost_ticket`.`ticket_id`) left join `ost_ticket_status` on(`ost_ticket`.`status_id` = `ost_ticket_status`.`id`)] Table 'db_osti434.ost_equipment_ticket' doesn't exist
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables!

**Comment by poctob** [comment]
try getting the latest code from upstream and see if takes care of this problem

**Comment by Justproof** [comment]
Will do. I'll let you know if it works.

**Comment by Justproof** [comment]
That did it. Thanks!

**Comment by Justproof** [comment]
When clicking the root of the applications tab, should there be a scp/apps.php file in the root? I just get a 404 error.
