### ISSUE TITLE
Mysql Error

### ISSUE THREAD

**Issue by mahathir83** [poctob/OSTEquipmentPlugin#57]
I'm getting this error, even I allow all access to my db user. I also use the latest code. I'm using osticket v1.10 and mysql v5.7.18

![equippluginerror](https://cloud.githubusercontent.com/assets/27938055/25647354/de4ef74c-2ff3-11e7-8fc5-e2396ff9fac0.png)

**Comment by EBS-DarkD** [comment]
I'm seeing the same issue/results on osticket v1.10 and MySql 5.5.57
It's reporting a syntax error in Alter table `ost_equipment` near the DROP INDEX `name` at line 5

For me it's also reporting that the table ost_ticket_event doesn't exist when it's trying to create trigger `ost_ticket_event_AINS`

The database account I'm using has full rights on the database

**Comment by poctob** [comment]
There other issues with OSTicket v1.10 where this plugin doesn't work. New version is in development.
