### ISSUE TITLE
unable to upgrade database tables

### ISSUE THREAD

**Issue by jeclink** [poctob/OSTEquipmentPlugin#58]
Note the following error . the key is at the end.
It says ost_equipment_ticket doesn't exist.  I have used a different prefix than 'ost' for my database table.
Is there a way to have plugin reference the correct table prefix.

Jim C.

[ALTER TABLE `calu_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) NOT NULL , ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` INT NULL AFTER `staff_id` 
DROP INDEX `name`] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 
'DROP INDEX `name`' at line 5[CREATE VIEW `calu_EquipmentTicketView` AS select `calu_equipment_ticket`.`equipment_id` AS `equipment_id`, `calu_equipment_ticket`.`ticket_id` AS `ticket_id`,
 `calu_equipment_ticket`.`created` AS `created`, `calu_equipment`.`category_id` AS `category_id`, `calu_equipment`.`is_active` AS `is_active`, 
 `calu_ticket_status`.`state` AS `status` from `ost_equipment_ticket` left join `ost_equipment` on(`ost_equipment_ticket`.`equipment_id` = `ost_equipment`.`equipment_id`)
 left join `ost_ticket` on(`ost_equipment_ticket`.`ticket_id` = `ost_ticket`.`ticket_id`)
 left join `ost_ticket_status` on(`ost_ticket`.`status_id` = `ost_ticket_status`.`id`)] Table 'ciu_support.ost_equipment_ticket' doesn't exist
Error parsing SQL schema! Get help from developers (#4)
Upgrade configuration error. Unable to upgrade database tables!

I was able to edit the references in sql files to  ost_  table reference. after doing this I receive the following error. This time is is saying ticket_event table does not exist in my Osticket installation.
I  have installed  Osticket 1.10  .  I do not see a Create Table command for ticket_event table in Plugins'  install Sql files.  

[ALTER TABLE `calu_equipment` CHANGE COLUMN `name` `asset_id` VARCHAR(255) NOT NULL , ADD COLUMN `staff_id` INT NULL AFTER `is_active`, ADD COLUMN `user_id` INT NULL AFTER `staff_id` DROP INDEX `name`] 
[CREATE TRIGGER `calu_ticket_event_AINS` AFTER INSERT ON `calu_ticket_event` FOR EACH ROW BEGIN IF NEW.state='closed' THEN SET @equipment_id = (SELECT equipment_id FROM `calu_equipment_ticket` WHERE ticket_id=NEW.ticket_id LIMIT 1); IF ((@equipment_id IS NOT NULL) AND (@equipment_id>0)) THEN SET @open_ticks = (SELECT COUNT(ticket_id) FROM `calu_EquipmentTicketView` WHERE equipment_id = @equipment_id AND `status` != 'closed'); IF @open_ticks = 0 THEN SET @status_id = (SELECT status_id FROM `calu_equipment_status` WHERE baseline=1 LIMIT 1); IF ((@status_id IS NOT NULL) AND (@status_id>0)) THEN UPDATE `calu_equipment` SET status_id = @status_id WHERE equipment_id = @equipment_id; END IF; END IF; END IF; ELSEIF NEW.state='created' THEN SET @status_id = (SELECT status_id FROM `calu_EquipmentFormView` WHERE ticket_id= NEW.ticket_id AND field_label='Status' LIMIT 1); SET @asset_id = (SELECT value FROM `calu_EquipmentFormView` WHERE ticket_id= NEW.ticket_id AND field_label='Asset ID' LIMIT 1); IF( @asset_id IS NULL) THEN SET @asset_id_str = (SELECT value FROM `calu_EquipmentFormView` WHERE ticket_id= NEW.ticket_id AND field_label='Equipment' LIMIT 1); SET @asset_id = (SELECT SUBSTRING_INDEX(@asset_id_str, 'Asset_ID:', -1)); SET @asset_id = SUBSTRING(@asset_id, 1, CHAR_LENGTH(@asset_id) - 2); END IF; SET @equipment_id = (SELECT equipment_id FROM `calu_equipment` WHERE asset_id= @asset_id);	IF ((@status_id IS NOT NULL) AND (@status_id >0)) AND ((@equipment_id IS NOT NULL) AND (@equipment_id >0)) THEN	UPDATE `calu_equipment` SET status_id = @status_id WHERE equipment_id=@equipment_id; INSERT INTO `calu_equipment_ticket` (equipment_id, ticket_id, created) VALUES (@equipment_id, NEW.ticket_id, NOW()); END IF; END IF; END] Table 'ciu_support.calu_ticket_event' doesn't exist

**Comment by jeclink** [comment]
I was able to create ticket_event table manually and then installation completed.
I only want to enable the back end of the plugin. when I attempted to open the  Equipment app I got an "access error" and program died. I commented out the following programs lines in dispatcher.php to stop this error and open the equipment app. Does any one know the reason for this program code


if ( basename($_SERVER['SCRIPT_NAME']) ==basename(__FILE__))
die("Access denied");
CREATE TABLE `calu_ticket_event` (
  `ticket_id` int(11) unsigned NOT NULL default '0',
  `staff_id` int(11) unsigned NOT NULL,
  `team_id` int(11) unsigned NOT NULL,
  `dept_id` int(11) unsigned NOT NULL,
  `topic_id` int(11) unsigned NOT NULL,
  `state` enum('created','closed','reopened','assigned','transferred','overdue') NOT NULL,
  `staff` varchar(255) NOT NULL default 'SYSTEM',
  `timestamp` datetime NOT NULL,
  KEY `ticket_state` (`ticket_id`, `state`, `timestamp`),
  KEY `ticket_stats` (`timestamp`, `state`)
) DEFAULT CHARSET=utf8;

**Comment by poctob** [comment]
The plugin doesn't currently work with 1.10, new version is in the development

**Comment by jeclink** [comment]
Thanks , I will wait for the new version

**Comment by dgiaquinta92** [comment]
Hello! Is there any solution to this problem?
Do you know when an update compatible with version 1.10 will be released?
Thanks for your contributions!
