### ISSUE TITLE
OSTE Equipment plug in, Displaying  Get help from developers (#4)

### ISSUE THREAD

**Issue by derek68** [poctob/OSTEquipmentPlugin#59]
Hi All

I have installed and tried to follow the install plug in guide, but I am getting errors when I turn on the plug in.  Can anyone please help me to fix.
Im sunning Ubuntu 16.04 OSticket v1.10 and the plug in verson 1.9.4.  Please see the print screen for the long error.

![image](https://user-images.githubusercontent.com/22875102/28760419-61da548a-75ea-11e7-95e6-c43855769cc0.png)

Thank you in advance.

**Comment by poctob** [comment]
The plugin doesn't work with OSTicket 1.10. New version is in development.

**Comment by derek68** [comment]
Sorry I feel like a fool now.  Cant wait to a new version is built.

**Comment by learn-by-flying** [comment]
Is there a timeline for the update?
