### ISSUE TITLE
Generate Asset ID

### ISSUE THREAD

**Issue by DaAntidote** [poctob/OSTEquipmentPlugin#6]
An enhancement would be if the equipment plugin would generate a unique Asset ID as it is created. This could then be used to define equipment on the front end page as well as the backend.

**Comment by aarobc** [comment]
This  is really Ideal, you could then generate bar-code labels based on the asset ID for streamlined item query

**Comment by DaAntidote** [comment]
Is it likely this will get included in 1.9.2B?

**Comment by poctob** [comment]
Yes, added to the milestone.
