### ISSUE TITLE
View tickets by category

### ISSUE THREAD

**Issue by DaAntidote** [poctob/OSTEquipmentPlugin#8]
last one... :)
Enhancement;
On the support staff panel ticket tab add functionality to be able to view tickets by Asset Category. Perhaps via dropdown to save real estate.

**Comment by poctob** [comment]
Committed to the archive.  The solution was a bit different from your proposal but still achieves the same thing.  

Extra columns were added under Applications->Equipment Categories page to show total count of open and closed tickets.  These values are links that will take you to the display page listing open or closed tickets for a particular category.

![screenshot-2](https://cloud.githubusercontent.com/assets/4343084/3529660/0b47f312-079c-11e4-8eb2-3b37b69d52c3.png)

![screenshot-3](https://cloud.githubusercontent.com/assets/4343084/3529663/0f8d73f2-079c-11e4-886b-335d962d353b.png)

**Comment by helmyshankly** [comment]
why is my equiment categories does not have 'Open Tickets' and Closed Tickets' like yours? @poctob

**Comment by poctob** [comment]
Because this is the pre-release code.  You can try pulling it directly from the repo if you want.

**Comment by DaAntidote** [comment]
OK GREAT THANKS.

On 11 July 2014 17:04, poctob notifications@github.com wrote:

> Because this is the pre-release code. You can try pulling it directly from
> the repo if you want.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poctob/OSTEquipmentPlugin/issues/8#issuecomment-48718568
> .

## 

Mart Hough
p.+925 1798 9025

**Comment by DaAntidote** [comment]
Im not that familiar with github, and maybe I didnt do it correctly, but I
tried downloading the code from here

https://github.com/poctob/OSTEquipmentPlugin

I wasnt sure about the upgrade process so tried installing it into a fresh
test install of osTicket.
I get a whole lot of database errors across the top of the screen and the
equipment dashboard refers to dashboard\equipment which doesnt exist in the
folder structure after installation of the plugin.

I'm sure I have something wrong, so if its obvious can you let me know. I'd
be happy to run through and test it out before you release it.
I'm pretty keen to see how the asset ID is implemented too. (I'm getting
ready to print asset stickers!)

On 12 July 2014 07:36, Mart Hough mart@fle33.com wrote:

> OK GREAT THANKS.
> 
> On 11 July 2014 17:04, poctob notifications@github.com wrote:
> 
> > Because this is the pre-release code. You can try pulling it directly
> > from the repo if you want.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/poctob/OSTEquipmentPlugin/issues/8#issuecomment-48718568
> > .
> 
> ## 
> 
> Mart Hough
> p.+925 1798 9025

## 

Mart Hough
p.+925 1798 9025

**Comment by poctob** [comment]
I will update installation instructions in the next couple days.

**Comment by DaAntidote** [comment]
ok thanks.

On 21 July 2014 19:34, poctob notifications@github.com wrote:

> I will update installation instructions in the next couple days.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poctob/OSTEquipmentPlugin/issues/8#issuecomment-49605567
> .

## 

Mart Hough
p.+925 1798 9025

**Comment by poctob** [comment]
See if you can get it going with the latest install/upgrade instructions.  Please let me know if something isn't working.

**Comment by DaAntidote** [comment]
OK will do today. Thanks.

On 22 July 2014 06:43, poctob notifications@github.com wrote:

> See if you can get it going with the latest install/upgrade instructions.
> Please let me know if something isn't working.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/poctob/OSTEquipmentPlugin/issues/8#issuecomment-49685178
> .

## 

Mart Hough
p.+925 1798 9025
