### ISSUE TITLE
Select equipment by serial instead of the drop down when creating new ticket

### ISSUE THREAD

**Issue by aarobc** [poctob/OSTEquipmentPlugin#9]
For situations where there are dozens of hardware devices in each category, it will very quickly become impractical for users to select their specific device via a drop down when they create the ticket. 

Instead, offer a field where they can enter their device serial number or id number. perhaps validate it upon submission.

**Comment by DaAntidote** [comment]
Or Asset ID, if that functionality becomes available.

**Comment by poctob** [comment]
Updated to use asset ID, which can be typed in or selected from the drop down.
